[package]
name = "lmul"
version = "0.1.0"
edition = "2024"

[dependencies]
tfhe = { version = "=1.2", features = ["boolean", "shortint", "integer", "gpu"] }
once_cell = "1.19.0"
rand = "0.8"
rand_distr = "0.4"     
rayon = "*"
half = "2"
ndarray = "0.15"
ndarray-npy = "0.8"
rand_chacha = "0.3"

[features]
exact = []
lmul = []
pam = []
default = []  