[package]
name = "TFHE_Based_Floating_Point_Neural_Network_Training"
version = "0.1.0"
edition = "2024"

[dependencies]
tfhe = { version = "=1.3", features = ["boolean", "shortint", "integer", "gpu"] }
once_cell = "1.19.0"
rand = "0.8"
rand_distr = "0.4"     
rayon = "*"
half = "2"
ndarray = "0.15"
ndarray-npy = "0.8"
rand_chacha = "0.3"
dhat = "0.3.3"
serde = { version = "1.0.228", features = ["derive"] }

[features]
exact = []
lmul = []
pam = []
default = ["lmul"] 
